// Code generated by rice embed-go; DO NOT EDIT.
package databases

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "202406101000_create_table_status.up.sql",
		FileModTime: time.Unix(1718005680, 0),

		Content: string("CREATE TABLE status (\r\n  id VARCHAR(255) NOT NULL,\r\n  name VARCHAR(255) NOT NULL,\r\n  PRIMARY KEY (id)\r\n);"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "202406101001_create_table_users.up.sql",
		FileModTime: time.Unix(1718026378, 0),

		Content: string("CREATE TABLE users (\r\n  id VARCHAR(255) NOT NULL,\r\n  name VARCHAR(255) NOT NULL,\r\n  email VARCHAR(255) NOT NULL,\r\n  country_calling_code VARCHAR(255) NOT NULL,\r\n  phone_number VARCHAR(255) NOT NULL,\r\n  password VARCHAR(255) NOT NULL,\r\n\r\n  gender_id TINYINT DEFAULT 1,\r\n  birth_date DATE DEFAULT (CURRENT_DATE),\r\n  height TINYINT unsigned DEFAULT 0,\r\n  about_me LONGTEXT DEFAULT NULL,\r\n\r\n  status_id VARCHAR(255) DEFAULT \"1\",\r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by VARCHAR(255) NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by VARCHAR(255) NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_email (email)\r\n);"),
	}
	file4 := &embedded.EmbeddedFile{
		Filename:    "202406101002_create_table_user_preferences.up.sql",
		FileModTime: time.Unix(1718024959, 0),

		Content: string("CREATE TABLE user_preferences (\r\n  id VARCHAR(255) NOT NULL,\r\n  user_id VARCHAR(255) NOT NULL,\r\n\r\n  search_distance TINYINT DEFAULT 50,\r\n  school_name VARCHAR(255) DEFAULT \"\",\r\n  drinking_frequency_id TINYINT DEFAULT 1,\r\n  smoking_frequency_id TINYINT DEFAULT 1,\r\n  workout_frequency_id TINYINT DEFAULT 1,\r\n  pet_id TINYINT DEFAULT 1,\r\n\r\n  communication_style_id TINYINT DEFAULT 1,\r\n  love_language_id TINYINT DEFAULT 1,\r\n  education_level_id TINYINT DEFAULT 1,\r\n  zodiac_id TINYINT DEFAULT 1,\r\n  \r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by INT NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by INT NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_user_id (user_id)\r\n);"),
	}
	file5 := &embedded.EmbeddedFile{
		Filename:    "202406101003_create_table_user_pictures.up.sql",
		FileModTime: time.Unix(1718024969, 0),

		Content: string("CREATE TABLE user_pictures (\r\n  id VARCHAR(255) NOT NULL,\r\n  user_id VARCHAR(255) NOT NULL,\r\n  img_url VARCHAR(255) DEFAULT \"\",\r\n  is_main TINYINT DEFAULT 0,\r\n  \r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by INT NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by INT NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_user_id (user_id)\r\n);"),
	}
	file6 := &embedded.EmbeddedFile{
		Filename:    "202406101400_create_table_genders.up.sql",
		FileModTime: time.Unix(1718005686, 0),

		Content: string("CREATE TABLE genders (\r\n  id VARCHAR(255) NOT NULL,\r\n  name VARCHAR(255) NOT NULL,\r\n  PRIMARY KEY (id)\r\n);"),
	}
	file7 := &embedded.EmbeddedFile{
		Filename:    "202406101401_insert_gender_data.up.sql",
		FileModTime: time.Unix(1718005783, 0),

		Content: string("INSERT INTO\r\n  genders (id, name)\r\nVALUES\r\n  (1, 'Male'), (2, 'Female');"),
	}
	file8 := &embedded.EmbeddedFile{
		Filename:    "202406101500_create_table_user_swipes.up.sql",
		FileModTime: time.Unix(1718024969, 0),

		Content: string("CREATE TABLE user_swipes (\r\n  id VARCHAR(255) NOT NULL,\r\n  user_id VARCHAR(255) NOT NULL,\r\n  display_user_id VARCHAR(255) NOT NULL,\r\n  action_id TINYINT DEFAULT 0,\r\n\r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by INT NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by INT NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_user_id (user_id)\r\n);"),
	}
	file9 := &embedded.EmbeddedFile{
		Filename:    "202406101501_create_table_user_matches.up.sql",
		FileModTime: time.Unix(1718024969, 0),

		Content: string("CREATE TABLE user_matches (\r\n  id VARCHAR(255) NOT NULL,\r\n  user_id VARCHAR(255) NOT NULL,\r\n  display_user_id VARCHAR(255) NOT NULL,\r\n\r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by INT NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by INT NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_user_id (user_id)\r\n);"),
	}
	filea := &embedded.EmbeddedFile{
		Filename:    "202406101502_create_table_actions.up.sql",
		FileModTime: time.Unix(1718009008, 0),

		Content: string("CREATE TABLE actions (\r\n  id VARCHAR(255) NOT NULL,\r\n  name VARCHAR(255) NOT NULL,\r\n  PRIMARY KEY (id)\r\n);"),
	}
	fileb := &embedded.EmbeddedFile{
		Filename:    "202406101503_insert_actions_data.up.sql",
		FileModTime: time.Unix(1718009044, 0),

		Content: string("INSERT INTO\r\n  actions (id, name)\r\nVALUES\r\n  (0, 'Pass'), (1, 'Like');"),
	}
	filec := &embedded.EmbeddedFile{
		Filename:    "202406101600_create_user_premium.up.sql",
		FileModTime: time.Unix(1718024969, 0),

		Content: string("CREATE TABLE user_premium (\r\n  id VARCHAR(255) NOT NULL,\r\n  user_id VARCHAR(255) NOT NULL,\r\n  bought_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  expired_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n\r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by VARCHAR(255) NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by VARCHAR(255) NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_user_id (user_id)\r\n);"),
	}
	filed := &embedded.EmbeddedFile{
		Filename:    "202406101601_create_premium_packages.up.sql",
		FileModTime: time.Unix(1718024969, 0),

		Content: string("CREATE TABLE premium_packages (\r\n  id VARCHAR(255) NOT NULL,\r\n  name VARCHAR(255) NOT NULL,\r\n  description VARCHAR(255) DEFAULT \"\",\r\n  price DECIMAL(10, 2) NOT NULL,\r\n  duration INT NOT NULL,\r\n\r\n  status_id VARCHAR(255) DEFAULT \"1\",\r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by VARCHAR(255) NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by VARCHAR(255) NULL,\r\n  PRIMARY KEY (id)\r\n);"),
	}
	filee := &embedded.EmbeddedFile{
		Filename:    "202406101602_insert_premium_packages_data.up.sql",
		FileModTime: time.Unix(1718025348, 0),

		Content: string("INSERT INTO\r\n  premium_packages (id,name, price, duration, description)\r\nVALUES\r\n  (\"532c01a5-272b-11ef-b37b-782b46514cf7\", 'Jomblo', 99000, 1, \"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac lectus tortor. Fusce eleifend euismod sapien.\"),\r\n  (\"67ad7f79-272b-11ef-b37b-782b46514cf7\", 'Jomblo Pasrah', 249000, 3, \"Maecenas iaculis pellentesque ante, et condimentum ligula tempus vel. Nulla sit amet consequat sapien, eu efficitur elit. Donec commodo nisl sit amet pulvinar dictum.\"),\r\n  (\"6d9d5c52-272b-11ef-b37b-782b46514cf7\", 'Jomblo Ngenes', 549000, 6, \"Praesent id nisl ligula. Sed leo odio, ornare et metus sed, dignissim maximus ligula. \"),\r\n  (\"74809a2f-272b-11ef-b37b-782b46514cf7\", 'Jomblo Putus Asa', 999000, 12, \"Nam nisi diam, gravida ut accumsan in, mattis sit amet mauris. Quisque sit amet leo ex. Fusce malesuada risus ante, id eleifend lacus fermentum nec. Suspendisse potenti.\");"),
	}
	filef := &embedded.EmbeddedFile{
		Filename:    "202406102030_create_table_user_actions.up.sql",
		FileModTime: time.Unix(1718027969, 0),

		Content: string("CREATE TABLE user_actions (\r\n  id VARCHAR(255) PRIMARY KEY NOT NULL,\r\n  user_id VARCHAR(255) DEFAULT NULL,\r\n  table_name VARCHAR(200) DEFAULT NULL,\r\n  action VARCHAR(100) DEFAULT NULL,\r\n  action_value INT DEFAULT 0,\r\n  ref_id VARCHAR(255) DEFAULT '0',\r\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP\r\n);"),
	}
	fileg := &embedded.EmbeddedFile{
		Filename:    "202406102031_insert_status_data.up.sql",
		FileModTime: time.Unix(1718027154, 0),

		Content: string("INSERT INTO\r\n  status (id, name)\r\nVALUES\r\n  ('0', 'Inactive'),\r\n  ('1', 'Active');"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1718027091, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "202406101000_create_table_status.up.sql"
			file3, // "202406101001_create_table_users.up.sql"
			file4, // "202406101002_create_table_user_preferences.up.sql"
			file5, // "202406101003_create_table_user_pictures.up.sql"
			file6, // "202406101400_create_table_genders.up.sql"
			file7, // "202406101401_insert_gender_data.up.sql"
			file8, // "202406101500_create_table_user_swipes.up.sql"
			file9, // "202406101501_create_table_user_matches.up.sql"
			filea, // "202406101502_create_table_actions.up.sql"
			fileb, // "202406101503_insert_actions_data.up.sql"
			filec, // "202406101600_create_user_premium.up.sql"
			filed, // "202406101601_create_premium_packages.up.sql"
			filee, // "202406101602_insert_premium_packages_data.up.sql"
			filef, // "202406102030_create_table_user_actions.up.sql"
			fileg, // "202406102031_insert_status_data.up.sql"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`./migrations`, &embedded.EmbeddedBox{
		Name: `./migrations`,
		Time: time.Unix(1718027091, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"202406101000_create_table_status.up.sql":           file2,
			"202406101001_create_table_users.up.sql":            file3,
			"202406101002_create_table_user_preferences.up.sql": file4,
			"202406101003_create_table_user_pictures.up.sql":    file5,
			"202406101400_create_table_genders.up.sql":          file6,
			"202406101401_insert_gender_data.up.sql":            file7,
			"202406101500_create_table_user_swipes.up.sql":      file8,
			"202406101501_create_table_user_matches.up.sql":     file9,
			"202406101502_create_table_actions.up.sql":          filea,
			"202406101503_insert_actions_data.up.sql":           fileb,
			"202406101600_create_user_premium.up.sql":           filec,
			"202406101601_create_premium_packages.up.sql":       filed,
			"202406101602_insert_premium_packages_data.up.sql":  filee,
			"202406102030_create_table_user_actions.up.sql":     filef,
			"202406102031_insert_status_data.up.sql":            fileg,
		},
	})
}
