// Code generated by rice embed-go; DO NOT EDIT.
package databases

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "202406101000_create_table_status.up.sql",
		FileModTime: time.Unix(1717341152, 0),

		Content: string("CREATE TABLE status (\r\n  id VARCHAR(255) NOT NULL,\r\n  name VARCHAR(255) NOT NULL,\r\n  PRIMARY KEY (id),\r\n);"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "202406101001_create_table_users.up.sql",
		FileModTime: time.Unix(1717998971, 0),

		Content: string("CREATE TABLE users (\r\n  id VARCHAR(255) DEFAULT UUID() NOT NULL,\r\n  name VARCHAR(255) NOT NULL,\r\n  email VARCHAR(255) NOT NULL,\r\n  country_calling_code VARCHAR(255) NOT NULL,\r\n  phone_number VARCHAR(255) NOT NULL,\r\n  password VARCHAR(255) NOT NULL,\r\n\r\n  gender TINYINT DEFAULT 1,\r\n  birth_date DATE DEFAULT CURRENT_DATE,\r\n  height TINYINT DEFAULT 0,\r\n  about_me LONGTEXT DEFAULT NULL,\r\n\r\n  status_id VARCHAR(255) DEFAULT \"1\",\r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by VARCHAR(255) NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by VARCHAR(255) NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_username (username),\r\n  INDEX index_email (email)\r\n);"),
	}
	file4 := &embedded.EmbeddedFile{
		Filename:    "202406101002_create_table_user_preferences.up.sql",
		FileModTime: time.Unix(1717999299, 0),

		Content: string("CREATE TABLE user_preferences (\r\n  id VARCHAR(255) DEFAULT UUID() NOT NULL,\r\n  user_id VARCHAR(255) NOT NULL,\r\n\r\n  search_distance TINYINT DEFAULT 50,\r\n  school_name VARCHAR(255) DEFAULT \"\",\r\n  drinking_frequency_id TINYINT DEFAULT 1,\r\n  smoking_frequency_id TINYINT DEFAULT 1,\r\n  workout_frequency_id TINYINT DEFAULT 1,\r\n  pet_id TINYINT DEFAULT 1,\r\n\r\n  communication_style_id TINYINT DEFAULT 1,\r\n  love_language_id TINYINT DEFAULT 1,\r\n  education_level_id TINYINT DEFAULT 1,\r\n  zodiac_id TINYINT DEFAULT 1,\r\n  \r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by INT NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by INT NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_user_id (user_id)\r\n);"),
	}
	file5 := &embedded.EmbeddedFile{
		Filename:    "202406101003_create_table_user_pictures.up.sql",
		FileModTime: time.Unix(1717999291, 0),

		Content: string("CREATE TABLE user_pictures (\r\n  id VARCHAR(255) DEFAULT UUID() NOT NULL,\r\n  user_id VARCHAR(255) NOT NULL,\r\n  img_url VARCHAR(255) DEFAULT \"\",\r\n  is_main TINYINT DEFAULT 0,\r\n  \r\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  created_by INT NULL,\r\n  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\r\n  updated_by INT NULL,\r\n  PRIMARY KEY (id),\r\n  INDEX index_user_id (user_id)\r\n);"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1717998753, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "202406101000_create_table_status.up.sql"
			file3, // "202406101001_create_table_users.up.sql"
			file4, // "202406101002_create_table_user_preferences.up.sql"
			file5, // "202406101003_create_table_user_pictures.up.sql"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`./migrations`, &embedded.EmbeddedBox{
		Name: `./migrations`,
		Time: time.Unix(1717998753, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"202406101000_create_table_status.up.sql":           file2,
			"202406101001_create_table_users.up.sql":            file3,
			"202406101002_create_table_user_preferences.up.sql": file4,
			"202406101003_create_table_user_pictures.up.sql":    file5,
		},
	})
}
